name = "PtrArrays"
uuid = "43287f4e-b6f4-7ad1-bb20-aadabca52c3d"
authors = ["Lilith Orion Hafner <lilithhafner@gmail.com> and contributors"]
version = "1.3.0"

[deps]
CheckedSizeProduct = "1b2cc9da-92e3-4b71-9788-30fc110eefda"

[compat]
CheckedSizeProduct = "1"
julia = "1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
